import { Article, TrendingKeyword, SearchResult, SearchFilters, Citation, User, UserBookmark, UserHistory, DashboardStats } from '@/types';

const indonesianArticles: Article[] = [
  {
    id: 'article-id-1',
    title: 'Klasifikasi Metode Persalinan pada Ibu Hamil Menggunakan Algoritma Random Forest Berbasis Mobile',
    authors: [
      { name: 'Dewi Marini Umi Atmaja', affiliation: 'Universitas Medika Suherman' },
      { name: 'Arif Rahman Hakim', affiliation: 'Universitas Medika Suherman' },
      { name: 'Amat Basri', affiliation: 'Universitas Medika Suherman' },
      { name: 'Andri Ariyanto', affiliation: 'Universitas Jenderal Achmad Yani' },
    ],
    year: 2023,
    publisher: 'Universitas Muhammadiyah Purwokerto',
    journal: 'JRST: Jurnal Riset Sains dan Teknologi',
    volume: '7',
    issue: '2',
    pages: '161-168',
    doi: '10.30595/jrst.v7i2.16705',
    citationCount: 12,
    abstract: 'Tren angka kematian ibu pada saat melahirkan masih tinggi di Indonesia, yakni sekitar 300 per 100.000 kelahiran. Pemerintah Indonesia berencana untuk menurunkan angka tersebut menjadi 183 per 100.000 kelahiran pada tahun 2024 mendatang. Salah satu faktor penyebab kematian ibu hamil di Indonesia disebabkan oleh hipertensi dan terjadinya pendarahan pada saat melahirkan dan dibutuhkannya metode penanganan dalam persalinan. Metode persalinan pada ibu hamil dapat diklasifikasikan sesuai dengan kondisi ibu untuk menghindari risiko kematian ibu akibat pemilihan metode persalinan yang tidak tepat. Permasalahan tersebut dapat diselesaikan dengan memanfaatkan teknologi Machine Learning menggunakan algoritma random forest, dengan tujuan untuk membangun sebuah sistem yang dapat mengklasifikasi metode persalinan yang tepat berdasarkan kumpulan data persalinan ibu hamil yang telah disediakan.',
    keywords: ['persalinan', 'random forest', 'android', 'machine learning', 'klasifikasi'],
    openAccess: true,
    pdfUrl: 'https://jurnalnasional.ump.ac.id/index.php/JRST/article/view/16705',
    contentType: 'html',
    language: 'id',
    type: 'journal',
    subject: 'computer-science',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2023, 10, 21).toISOString(),
  },
  {
    id: 'article-id-2',
    title: 'Model Optimasi SVM Dengan PSO-GA dan SMOTE Dalam Menangani High Dimensional dan Imbalance Data Banjir',
    authors: [
      { name: 'Raenald Syaputra', affiliation: 'Universitas Muhammadiyah Kalimantan Timur' },
      { name: 'Taghfirul Azhima Yoga Siswa', affiliation: 'Universitas Muhammadiyah Kalimantan Timur' },
      { name: 'Wawan Joko Pranoto', affiliation: 'Universitas Muhammadiyah Kalimantan Timur' },
    ],
    year: 2024,
    publisher: 'Center for Research and Community Service, Institut Informatika Indonesia Surabaya',
    journal: 'Teknika',
    volume: '13',
    issue: '2',
    pages: '273-282',
    doi: '10.34148/teknika.v13i2.876',
    citationCount: 8,
    abstract: 'Banjir merupakan salah satu bencana alam yang sering terjadi di Indonesia, termasuk di Kota Samarinda dengan 18-33 titik desa terdampak dari tahun 2018-2021. Penggunaan machine learning dalam mengklasifikasi bencana banjir sangat penting untuk memprediksi kejadian di masa mendatang. Penelitian ini bertujuan mengidentifikasi fitur-fitur yang diperoleh dari seleksi fitur Genetic Algorithm (GA) yang memiliki pengaruh terhadap akurasi klasifikasi data banjir Kota Samarinda menggunakan algoritma Support Vector Machine (SVM), serta meningkatkan akurasi klasifikasi data banjir di Kota Samarinda dengan mengimplementasikan algoritma SVM yang dikombinasikan dengan metode Synthetic Minority Oversampling Technique (SMOTE) untuk oversampling, seleksi fitur dengan GA dan optimasi menggunakan Particle Swarm Optimization (PSO).',
    keywords: ['klasifikasi banjir', 'svm', 'smote', 'ga', 'pso', 'machine learning'],
    openAccess: true,
    pdfUrl: 'https://ejournal.ikado.ac.id/index.php/teknika/article/view/876',
    language: 'id',
    type: 'journal',
    subject: 'computer-science',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2024, 6, 11).toISOString(),
  },
  {
    id: 'article-id-3',
    title: 'Sentiment Analysis using the Support Vector Machine Algorithm on Covid-19',
    authors: [
      { name: 'Adytyo Wahyu Nugroho', affiliation: 'Islamic University of Indragiri' },
      { name: 'Norhikmah Norhikmah', affiliation: 'Islamic University of Indragiri' },
    ],
    year: 2024,
    publisher: 'Islamic University of Indragiri',
    journal: 'Sistemasi: Jurnal Sistem Informasi',
    volume: '13',
    issue: '4',
    pages: '1758-1772',
    doi: '10.32520/stmsi.v13i4.3778',
    citationCount: 5,
    abstract: 'This massive development of information technology makes it easier for people lives in various fields, one of them is social media, social media that people use a lot to get information about news or events that are happening in Indonesia, one of which is social media Twitter which provides a lot of information for the people of Indonesia, one of which is information about Covid-19 which is currently rife in the territory of Indonesia. Sentiment analysis is a branch of Natural Language Processing (NLP) which can help determine the sentiments that occur in society. This study uses data in the form of tweets to carry out sentiment analysis obtained on Twitter social media.',
    keywords: ['sentiment analysis', 'support vector machine', 'covid-19', 'nlp', 'twitter'],
    openAccess: true,
    pdfUrl: 'https://sistemasi.ftik.unisi.ac.id/index.php/stmsi/article/view/3778',
    language: 'id',
    type: 'journal',
    subject: 'computer-science',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2024, 7, 15).toISOString(),
  },
  {
    id: 'article-id-2',
    title: 'Model Optimasi SVM Dengan PSO-GA dan SMOTE Dalam Menangani High Dimensional dan Imbalance Data Banjir',
    authors: [
      { name: 'Raenald Syaputra', affiliation: 'Universitas Muhammadiyah Kalimantan Timur' },
      { name: 'Taghfirul Azhima Yoga Siswa', affiliation: 'Universitas Muhammadiyah Kalimantan Timur' },
      { name: 'Wawan Joko Pranoto', affiliation: 'Universitas Muhammadiyah Kalimantan Timur' },
    ],
    year: 2024,
    publisher: 'Center for Research and Community Service, Institut Informatika Indonesia Surabaya',
    journal: 'Teknika',
    volume: '13',
    issue: '2',
    pages: '273-282',
    doi: '10.34148/teknika.v13i2.876',
    citationCount: 8,
    abstract: 'Banjir merupakan salah satu bencana alam yang sering terjadi di Indonesia, termasuk di Kota Samarinda dengan 18-33 titik desa terdampak dari tahun 2018-2021. Penggunaan machine learning dalam mengklasifikasi bencana banjir sangat penting untuk memprediksi kejadian di masa mendatang. Penelitian ini bertujuan mengidentifikasi fitur-fitur yang diperoleh dari seleksi fitur Genetic Algorithm (GA) yang memiliki pengaruh terhadap akurasi klasifikasi data banjir Kota Samarinda menggunakan algoritma Support Vector Machine (SVM), serta meningkatkan akurasi klasifikasi data banjir di Kota Samarinda dengan mengimplementasikan algoritma SVM yang dikombinasikan dengan metode Synthetic Minority Oversampling Technique (SMOTE) untuk oversampling, seleksi fitur dengan GA dan optimasi menggunakan Particle Swarm Optimization (PSO).',
    keywords: ['klasifikasi banjir', 'svm', 'smote', 'ga', 'pso', 'machine learning'],
    openAccess: true,
    pdfUrl: 'https://ejournal.ikado.ac.id/index.php/teknika/article/view/876',
    contentType: 'html',
    language: 'id',
    type: 'journal',
    subject: 'computer-science',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2024, 6, 11).toISOString(),
  },
  {
    id: 'article-id-3',
    title: 'Sentiment Analysis using the Support Vector Machine Algorithm on Covid-19',
    authors: [
      { name: 'Adytyo Wahyu Nugroho', affiliation: 'Islamic University of Indragiri' },
      { name: 'Norhikmah Norhikmah', affiliation: 'Islamic University of Indragiri' },
    ],
    year: 2024,
    publisher: 'Islamic University of Indragiri',
    journal: 'Sistemasi: Jurnal Sistem Informasi',
    volume: '13',
    issue: '4',
    pages: '1758-1772',
    doi: '10.32520/stmsi.v13i4.3778',
    citationCount: 5,
    abstract: 'This massive development of information technology makes it easier for people lives in various fields, one of them is social media, social media that people use a lot to get information about news or events that are happening in Indonesia, one of which is social media Twitter which provides a lot of information for the people of Indonesia, one of which is information about Covid-19 which is currently rife in the territory of Indonesia. Sentiment analysis is a branch of Natural Language Processing (NLP) which can help determine the sentiments that occur in society. This study uses data in the form of tweets to carry out sentiment analysis obtained on Twitter social media.',
    keywords: ['sentiment analysis', 'support vector machine', 'covid-19', 'nlp', 'twitter'],
    openAccess: true,
    pdfUrl: 'https://sistemasi.ftik.unisi.ac.id/index.php/stmsi/article/view/3778',
    contentType: 'html',
    language: 'id',
    type: 'journal',
    subject: 'computer-science',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2024, 7, 15).toISOString(),
  },
  {
    id: 'article-id-4',
    title: 'Evaluasi Manajemen Proyek',
    authors: [
      { name: 'Suryanto Suryanto', affiliation: 'Universitas Bina Nusantara' },
      { name: 'Sanyoto Gondodiyoto', affiliation: 'Sekolah Tinggi Akuntansi Negara' },
      { name: 'Desi N I', affiliation: 'Universitas Bina Nusantara' },
    ],
    year: 2009,
    publisher: 'Bina Nusantara University',
    journal: 'CommIT Journal',
    volume: '3',
    issue: '2',
    pages: '82-85',
    doi: '10.21512/commit.v3i2.520',
    citationCount: 12,
    abstract: 'The purpose of this study was to evaluate the project management and make suggestions to the problems being faced by the company. Many companies or individuals working on a project basis (project based), but many of those who do not manage the project well, even with no management at all and let the project flow as it is. Therefore, it needs a proper guidance and methods to support a project management information system.',
    keywords: ['project management', 'evaluation', 'information system'],
    openAccess: true,
    pdfUrl: 'https://journal.binus.ac.id/index.php/commit/article/view/520',
    contentType: 'html',
    language: 'en',
    type: 'journal',
    subject: 'computer-science',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2009, 9, 1).toISOString(),
  },
  {
    id: 'article-id-5',
    title: 'Evaluating User Experience of a Mobile Health Application Halodoc using User Experience Questionnaire and Usability Testing',
    authors: [
      { name: 'Mochammad Aldi Kushendriawan', affiliation: 'Universitas Indonesia' },
      { name: 'Harry Budi Santoso', affiliation: 'Universitas Indonesia' },
      { name: 'Panca O. Hadi Putra', affiliation: 'Universitas Indonesia' },
      { name: 'Martin Schrepp', affiliation: 'Universitas Indonesia' },
    ],
    year: 2021,
    publisher: 'Fakultas Ilmu Komputer, Universitas Indonesia',
    journal: 'Jurnal Sistem Informasi',
    volume: '17',
    issue: '1',
    pages: '1-15',
    doi: '',
    citationCount: 45,
    abstract: 'This paper aims to evaluate the user experience of a mobile health application called Halodoc to keep the user using the application and keep from losing a potential source of revenue for Halodoc. Halodoc is one of the companies that use the internet to provide health services for its users. This paper uses a mixed-method approach using User Experience Questionnaire (UEQ) and Usability Testing.',
    keywords: ['mobile health', 'usability testing', 'user experience', 'halodoc', 'mhealth'],
    openAccess: true,
    pdfUrl: 'https://jsi-tes.pusilkom.com/index.php/jsi/article/view/1063',
    contentType: 'html',
    language: 'en',
    type: 'journal',
    subject: 'computer-science',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2021, 11, 6).toISOString(),
  },
  {
    id: 'article-id-6',
    title: 'Students Learning Interest Using Computer and Android in Acid Base Teaching',
    authors: [
      { name: 'Milanda Putri', affiliation: 'Universitas Islam Negeri Sultan Syarif Kasim Riau' },
      { name: 'Yenni Kurniawati', affiliation: 'Universitas Islam Negeri Sultan Syarif Kasim Riau' },
    ],
    year: 2021,
    publisher: 'Universitas Negeri Malang',
    journal: 'J-PEK (Jurnal Pembelajaran Kimia)',
    volume: '6',
    issue: '2',
    pages: '63-71',
    doi: '10.17977/um026v6i22021p063',
    citationCount: 18,
    abstract: 'This research is motivated by the influence of high technology on education; hence educators need to choose the right technology device to use and compare student learning interests with and without the support of computer and android multimedia. It was quasi-experiment research with posttest only and non-equivalent control group designs.',
    keywords: ['multimedia', 'computer', 'android', 'learning interest', 'acid-base'],
    openAccess: true,
    pdfUrl: 'http://journal2.um.ac.id/index.php/j-pek/article/view/20390',
    contentType: 'html',
    language: 'id',
    type: 'journal',
    subject: 'education',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2021, 11, 1).toISOString(),
  },
  {
    id: 'article-id-7',
    title: 'Designing Mobile-Based Application for Quantifying IT Business Value',
    authors: [
      { name: 'Stanley Karouw', affiliation: 'Sam Ratulangi University Manado' },
    ],
    year: 2014,
    publisher: 'Fakultas Ilmu Komputer, Universitas Indonesia',
    journal: 'Jurnal Sistem Informasi',
    volume: '10',
    issue: '1',
    pages: '1-10',
    doi: '10.21609/jsi.v10i1.373',
    citationCount: 8,
    abstract: 'North Sulawesi province is fostering regional development towards a society which have values, prosperous and competitive cultures. Information Technology (IT) have become a key enabler to accelerate region developments. To optimize IT utilization, local government can used IT Valuation Matrix framework, to identify all IT Business Value which derived from each IT investing type, and then be quantify in reasonable and responsible manner.',
    keywords: ['IT business value', 'mobile application', 'agile', 'software development'],
    openAccess: true,
    pdfUrl: 'http://jsi1.cs.ui.ac.id/index.php/jsi/article/view/373',
    contentType: 'html',
    language: 'en',
    type: 'journal',
    subject: 'computer-science',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2014, 7, 1).toISOString(),
  },
  {
    id: 'article-id-8',
    title: 'The Effectiveness of Exercise Therapy on Reducing Pain in Osteoarthritis Patients: Literature Review',
    authors: [
      { name: 'Warsono Warsono', affiliation: 'Universitas Muhammadiyah Semarang' },
    ],
    year: 2020,
    publisher: 'Universitas Muhammadiyah Semarang',
    journal: 'Media Keperawatan Indonesia',
    volume: '3',
    issue: '2',
    pages: '99-105',
    doi: '10.26714/mki.3.2.2020.99-105',
    citationCount: 22,
    abstract: 'Osteoarthritis (OA) is a chronic joint disorder with damage to the joint cartilage, this causes a decrease in the functional ability and perform daily activities. So intervention is needed in reducing these problems to increase and maintain independence in carrying out training activities. This research used a systematic literature study approach obtained from PubMed database and Science Direct.',
    keywords: ['osteoarthritis', 'exercise therapy', 'pain', 'nursing', 'literature review'],
    openAccess: true,
    pdfUrl: 'https://jurnal.unimus.ac.id/index.php/MKI/article/view/11062',
    contentType: 'html',
    language: 'id',
    type: 'journal',
    subject: 'medicine',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2020, 5, 1).toISOString(),
  },
  {
    id: 'article-id-9',
    title: 'Terapi Spesialis Keperawatan Jiwa terhadap Klien dan Keluarga',
    authors: [
      { name: 'Winda Ratna Wulan', affiliation: 'Universitas Indonesia' },
      { name: 'Achir Yani S. Hamid', affiliation: 'Universitas Indonesia' },
      { name: 'Novy Helena', affiliation: 'Universitas Indonesia' },
    ],
    year: 2015,
    publisher: 'Fakultas Ilmu Keperawatan Universitas Indonesia',
    journal: 'Jurnal Keperawatan Indonesia',
    volume: '18',
    issue: '1',
    pages: '59-66',
    doi: '10.7454/jki.v18i1.399',
    citationCount: 35,
    abstract: 'Sejak Juli 2013, Rumah Sakit Provinsi Jawa Barat membuka Poli Konseling Psikiatri di Grha Atma yang melibatkan perawat spesialis keperawatan jiwa. Penelitian yang dilakukan adalah dengan menggunakan penelitian survei dengan metode kuantitatif dan menggunakan rancangan cross sectional.',
    keywords: ['poliklinik konseling', 'karakteristik klien', 'terapi spesialis keperawatan jiwa'],
    openAccess: true,
    pdfUrl: 'http://jki.ui.ac.id/index.php/jki/article/view/399',
    contentType: 'html',
    language: 'id',
    type: 'journal',
    subject: 'medicine',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2015, 2, 1).toISOString(),
  },
  {
    id: 'article-id-10',
    title: 'Strategies for Supporting Healthcare Workers Resilience and Mental Health During A Pandemic: A Scoping Review',
    authors: [
      { name: 'Eka Oktavianto', affiliation: 'STIKes Surya Global, Yogyakarta' },
      { name: 'I Made Moh. Yanuar Saifudin', affiliation: 'STIKes Surya Global, Yogyakarta' },
      { name: 'Gani Apriningtyas Budiyati', affiliation: 'STIKes Surya Global, Yogyakarta' },
    ],
    year: 2023,
    publisher: 'Fakultas Ilmu Keperawatan Universitas Indonesia',
    journal: 'Jurnal Keperawatan Indonesia',
    volume: '26',
    issue: '1',
    pages: '46-56',
    doi: '10.7454/jki.v26i1.2278',
    citationCount: 42,
    abstract: 'As a group, health workers are at risk of experiencing stress and mental health problems at work, which may negatively affect their resilience. This study assessed the effectiveness of mental health support strategies for health workers during the COVID-19 pandemic.',
    keywords: ['health workers', 'mental health', 'pandemic', 'resilience', 'scoping review'],
    openAccess: true,
    pdfUrl: 'https://jki.ui.ac.id/index.php/jki/article/view/1081',
    contentType: 'html',
    language: 'id',
    type: 'journal',
    subject: 'medicine',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2023, 2, 1).toISOString(),
  },
  {
    id: 'article-id-11',
    title: 'Implementation of brain gym and puzzle therapy and changes in cognitive function among elderly people with dementia in primary health care',
    authors: [
      { name: 'Lisdahayati Lisdahayati', affiliation: 'Poltekkes Kemenkes Palembang' },
      { name: 'I Gusti Ayu Putu Desy Rohana', affiliation: 'Poltekkes Kemenkes Palembang' },
      { name: 'Saprianto Saprianto', affiliation: 'Poltekkes Kemenkes Palembang' },
      { name: 'Gunardi Pome', affiliation: 'Poltekkes Kemenkes Palembang' },
    ],
    year: 2026,
    publisher: 'STIKes Al-Ma\'arif Baturaja',
    journal: 'Lentera Perawat',
    volume: '7',
    issue: '2',
    pages: '472-479',
    doi: '10.52235/lp.v7i2.773',
    citationCount: 3,
    abstract: 'Background: Dementia is a progressive decline in cognitive function that affects memory, thinking, behavior, and activities of daily living, particularly among older adults. This study aimed to describe changes in cognitive function among older adults before and after the implementation of brain gym and puzzle therapy.',
    keywords: ['cognitive dysfunction', 'dementia', 'exercise therapy', 'nursing care', 'primary health care'],
    openAccess: true,
    pdfUrl: 'https://jurnal.stikesalmaarif.ac.id/index.php/lenteraperawat/article/view/773',
    contentType: 'html',
    language: 'en',
    type: 'journal',
    subject: 'medicine',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2026, 5, 1).toISOString(),
  },
  {
    id: 'article-id-12',
    title: 'MEDIA PEMBELAJARAN BAHASA DAN SASTRA (STUDI PUSTAKA)',
    authors: [
      { name: 'Fina Nabilah Layaliya', affiliation: 'Universitas Negeri Semarang' },
      { name: 'Haryadi Haryadi', affiliation: 'Universitas Negeri Semarang' },
      { name: 'Nas Haryati Setyaningsih', affiliation: 'Universitas Negeri Semarang' },
    ],
    year: 2021,
    publisher: 'Program Studi Pendidikan Bahasa dan Sastra Indonesia',
    journal: 'Jurnal Pendidikan Bahasa dan Sastra Indonesia Metalingua',
    volume: '6',
    issue: '2',
    pages: '81-84',
    doi: '10.21107/metalingua.v6i2.12392',
    citationCount: 15,
    abstract: 'Penelitian ini merupakan penelitian kepustakaan yakni data-data atau bahan-bahan yang diperlukan berasal dari perpustakaan baik berupa buku, ensklopedi, kamus, jurnal, dokumen, maupun majalah. Media pembelajaran dibutuhkan dalam mata pelajaran yang diajarkan di sekolah, salah satunya mata pelajaran Bahasa Indonesia.',
    keywords: ['kepustakaan', 'media pembelajaran', 'bahasa dan sastra'],
    openAccess: true,
    pdfUrl: 'https://journal.trunojoyo.ac.id/metalingua/article/view/12392',
    contentType: 'html',
    language: 'id',
    type: 'journal',
    subject: 'education',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2021, 9, 1).toISOString(),
  },
  {
    id: 'article-id-13',
    title: 'Kompleksitas Kawin Siri: Antara Hukum Islam dan Undang-Undang Perkawinan di Indonesia',
    authors: [
      { name: 'Halil Khusairi', affiliation: 'Fakultas Syariah UIN Mataram' },
    ],
    year: 2022,
    publisher: 'Fakultas Syariah UIN Mataram',
    journal: 'Istinbath',
    volume: '21',
    issue: '1',
    pages: '1-15',
    doi: '10.20414/ijhi.v21i1.492',
    citationCount: 18,
    abstract: 'Perkawinan merupakan suatu kejadian yang sangat penting dalam kehidupan seseorang. Bagi Bangsa Indonesia yang memiliki alam pikiran magis (percaya pada hal-hal gaib), ritual perkawinan tidak hanya dipandang sebagai sebuah seremonial, tetapi juga peristiwa sakral. Penelitian ini merupakan penelitian pustaka (library research). Peneliti berusaha mengkaji konsep kawin sirri dalam pembaharuan hukum perkawinan Islam dan hukum perkawinan di Indonesia.',
    keywords: ['nikah siri', 'perkawinan', 'hukum Islam', 'fiqih', 'undang-undang'],
    openAccess: true,
    pdfUrl: 'https://istinbath.or.id/index.php/ijhi/article/view/492',
    contentType: 'html',
    language: 'id',
    type: 'journal',
    subject: 'islamic-law',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2022, 7, 1).toISOString(),
  },
  {
    id: 'article-id-14',
    title: 'Kitab Tajwid Nazm Batu Ngompal Tuan Guru Kyai Haji Muhammad Zainuddin Abdul Madjid',
    authors: [
      { name: 'Salim Rahmatullah', affiliation: 'Universiti Sultan Zainal Abidin (UniSZA), Malaysia' },
      { name: 'Mohd. Shafiee Bin Hamzah', affiliation: 'Universiti Sultan Zainal Abidin (UniSZA), Malaysia' },
    ],
    year: 2022,
    publisher: 'Sekolah Tinggi Agama Islam Sadra',
    journal: 'Tanzil: Jurnal Studi Al-Quran',
    volume: '4',
    issue: '2',
    pages: '119-134',
    doi: '10.20871/tjsq.v4i2.208',
    citationCount: 8,
    abstract: 'Para ulama di Nusantara menilai penting membaca al-Quran, sehingga mereka melakukan pengajaran-pengajaran ilmu al-Quran. Salah satunya di bidang tajwid dengan berbagai kitab yang aslinya berbahasa Arab, tetapi diterjemahkan dan diajarkan kepada para muridnya. Artikel ini mencoba mendeskripsikan dan melihat keunikan dari kitab tajwid Nadhom Batu Ngompal.',
    keywords: ['tajwid', 'al-Quran', 'arab-jawi', 'arudh science', 'ulama nusantara'],
    openAccess: true,
    pdfUrl: 'https://journal.sadra.ac.id/ojs/index.php/tanzil/article/view/208',
    contentType: 'html',
    language: 'en',
    type: 'journal',
    subject: 'islamic-studies',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2022, 6, 1).toISOString(),
  },
  {
    id: 'article-id-15',
    title: 'Manajemen Pembelajaran Ilmu Tajwid Melalui Nadhom Di Pesantren',
    authors: [
      { name: 'Azmi Islami', affiliation: 'Universitas Darunnajah Jakarta Indonesia' },
      { name: 'Imroatun Imroatun', affiliation: 'UIN Sultan Maulana Hasanuddin Banten Indonesia' },
      { name: 'Nurlaeli Nurlaeli', affiliation: 'UIN Sultan Maulana Hasanuddin Banten Indonesia' },
    ],
    year: 2023,
    publisher: 'Universitas Cokroaminoto Yogyakarta',
    journal: 'Asas wa Tandhim',
    volume: '3',
    issue: '1',
    pages: '21-30',
    doi: '10.47200/awtjhpsa.v3i1.2051',
    citationCount: 5,
    abstract: 'This research demonstrates how adult female students at the Pondok Pesantren Riyadul Awamil Islamic, Serang Regency, understand Ilm Tajwid utilizing nadhom in the book Tuhfatul Atfal Wal Ghilman Fi Tajwid al-Quran. This kitab kuning is used at Islamic boarding schools throughout Indonesia, even Southeast Asia as a manual for reading the Quran.',
    keywords: ['tajwid', 'nadhom', 'ilm tajwid', 'pesantren', 'quran'],
    openAccess: true,
    pdfUrl: 'https://jurnal.ucy.ac.id/index.php/awtjhpsa/article/view/2051',
    contentType: 'html',
    language: 'en',
    type: 'journal',
    subject: 'islamic-studies',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2023, 9, 1).toISOString(),
  },
  {
    id: 'article-id-16',
    title: 'Makna Zikir Bagi Jemaah Tarekat Naqshabandiyah Khalidiyah Majelis Pengkajian Tauhid Tasawuf Indonesia di Kota Gorontalo',
    authors: [
      { name: 'Rahmawati Rahmawati', affiliation: 'Institut Agama Islam Negeri Sultan Amai Gorontalo' },
      { name: 'Kasim Yahiji', affiliation: 'Institut Agama Islam Negeri Sultan Amai Gorontalo' },
      { name: 'Mustakimah Mustakimah', affiliation: 'Institut Agama Islam Negeri Sultan Amai Gorontalo' },
    ],
    year: 2018,
    publisher: 'Universitas Islam Negeri Sunan Ampel',
    journal: 'Teosofi: Jurnal Tasawuf dan Pemikiran Islam',
    volume: '8',
    issue: '2',
    pages: '325-350',
    doi: '10.15642/teosofi.2018.8.2.325-350',
    citationCount: 22,
    abstract: 'This article attempts to elaborate the existence of dhikr along with its meaning performed and hold by the members of the Majelis Pengkajian Tauhid Tasawuf Indonesia under the auspices of the Tarekat Naqshabandiyah Khalidiyah in Gorontalo City. The study indicates that dhikr is a substantially mandatory ritual that must be performed by the followers of the tarekat.',
    keywords: ['tauhid', 'tasawuf', 'dhikr', 'tarekat', 'naqshabandiyah'],
    openAccess: true,
    pdfUrl: 'http://teosofi.uinsby.ac.id/index.php/teosofi/article/view/234',
    contentType: 'html',
    language: 'en',
    type: 'journal',
    subject: 'islamic-studies',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2018, 11, 1).toISOString(),
  },
  {
    id: 'article-id-17',
    title: 'Qiraat Ashr and The Determination of The Concepts of Nasakh and Mansukh',
    authors: [
      { name: 'Ismail Abd Halim', affiliation: 'Faculty of Language Studies and Human Development Universiti Malaysia Kelantan' },
      { name: 'Azhar Muhammad', affiliation: 'Faculty of Language Studies and Human Development Universiti Malaysia Kelantan' },
      { name: 'M. Jismani Yusoff', affiliation: 'Department of Quran and Hadis, Sultan Ismail Petra International Islamic University College' },
    ],
    year: 2023,
    publisher: 'Sultan Ismail Petra International Islamic University College (KIAS)',
    journal: 'Rabbanica: Journal of Revealed Knowledge',
    volume: '4',
    issue: '1',
    pages: '55-76',
    doi: '',
    citationCount: 12,
    abstract: 'The concept of nasakh and mansukh is accepted by most scholars as one of the concepts in the interpretation of the Quran. However, some scholars deny the practice of this concept in interpreting the Quran. Verse 106 of Surah al-Baqarah is among the arguments used by most scholars in setting this concept.',
    keywords: ['nasakh', 'manshuk', 'abrogation', 'quran', 'qiraat', 'tafsir'],
    openAccess: true,
    pdfUrl: 'https://ejournals.kias.edu.my/index.php/rabbanica/article/view/268',
    contentType: 'html',
    language: 'en',
    type: 'journal',
    subject: 'islamic-studies',
    source: 'DOAJ',
    createdAt: new Date(2023, 4, 1).toISOString(),
  },
  {
    id: 'article-id-18',
    title: 'Living Hadis dalam Kegiatan Peringatan Maulid Nabi di Pesantren Sunan Ampel Jombang',
    authors: [
      { name: 'Faiqatul Khosyiah', affiliation: 'Program Studi Ilmu Hadis' },
    ],
    year: 2018,
    publisher: 'Program Studi Ilmu Hadis',
    journal: 'Jurnal Living Hadis',
    volume: '3',
    issue: '1',
    pages: '23-45',
    doi: '10.14421/livinghadis.2017.1363',
    citationCount: 35,
    abstract: 'Perayaan maulid nabi adalah salah satu tradisi yang banyak dilestarikan oleh masyarakat kita, utamanya di banyak pesantren di Jawa. Tradisi ini memiliki banyak corak cara pelaksanaan yang masing-masing memiliki ciri khas tersendiri. Melalui pendekatan fenomenologi dengan teori fungsional, tulisan ini mencoba memaparkan fenomena di dalam maulid ini.',
    keywords: ['hadis', 'living hadis', 'maulid nabi', 'pesantren', 'tradisi islam'],
    openAccess: true,
    pdfUrl: 'http://ejournal.uin-suka.ac.id/ushuluddin/Living/article/view/1363',
    contentType: 'html',
    language: 'id',
    type: 'journal',
    subject: 'islamic-studies',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2018, 4, 1).toISOString(),
  },
  {
    id: 'article-id-19',
    title: 'Pendidikan Multikultural pada Madrasah Aliyah Negeri 2 Kebumen',
    authors: [
      { name: 'Muchamad Solahudin', affiliation: 'Universitas Negeri Yogyakarta' },
    ],
    year: 2018,
    publisher: 'Universitas Negeri Yogyakarta',
    journal: 'Jurnal Pembangunan Pendidikan Fondasi dan Aplikasi',
    volume: '6',
    issue: '2',
    pages: '174-184',
    doi: '10.21831/jppfa.v6i2.23179',
    citationCount: 28,
    abstract: 'Menanamkan kesadaran multikultural kepada semua lapisan masyarakat menjadi sangat penting. Dari hasil analysis dapat dijelaskan bahwa sub materi yang menyangkut penanaman akidah atau tauhid tidak dapat diajarkan dengan menggunakan keempat model pendidikan multikultural.',
    keywords: ['akidah', 'tauhid', 'pendidikan multikultural', 'akhlak', 'madrasah'],
    openAccess: true,
    pdfUrl: 'https://journal.uny.ac.id/index.php/jppfa/article/view/23179',
    contentType: 'html',
    language: 'id',
    type: 'journal',
    subject: 'islamic-studies',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2018, 11, 1).toISOString(),
  },
  {
    id: 'article-id-20',
    title: 'Memperkuat Urf dalam Pengembangan Hukum Islam',
    authors: [
      { name: 'Ach Maimun', affiliation: 'Fakultas Syariah IAIN Madura' },
    ],
    year: 2017,
    publisher: 'Fakultas Syariah IAIN Madura',
    journal: 'Al-Ihkam: Jurnal Hukum dan Pranata Sosial',
    volume: '12',
    issue: '1',
    pages: '22-41',
    doi: '10.19105/al-ihkam.v12i1.1188',
    citationCount: 42,
    abstract: 'Sejauh ini, keberadaan urf sebagai sumber hukum Islam tidak menonjol. Padahal urf memiliki posisi penting untuk pengembangan Islam di Nusantara yang kaya budaya. Urf dapat menjadi pembendung kolompok yang anti terhadap tradisi lokal.',
    keywords: ['urf', 'hukum Islam', 'fiqih', 'tradisi lokal', 'iusjtihad'],
    openAccess: true,
    pdfUrl: 'http://ejournal.stainpamekasan.ac.id/index.php/alihkam/article/view/1188',
    contentType: 'html',
    language: 'id',
    type: 'journal',
    subject: 'islamic-law',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2017, 7, 1).toISOString(),
  },
  {
    id: 'article-id-21',
    title: 'Penguatan Resolusi Konflik Berbasis Tradisi Sunnah Nabi',
    authors: [
      { name: 'Alamsyah Alamsyah', affiliation: 'Universitas Islam Negeri Raden Intan Lampung' },
    ],
    year: 2020,
    publisher: 'Faculty of Sharia and Law UIN Sunan Gunung Djati Bandung',
    journal: 'Asy-Syari\'ah',
    volume: '22',
    issue: '1',
    pages: '1-20',
    doi: '10.15575/as.v22i1.8034',
    citationCount: 15,
    abstract: 'Tulisan ini mengkaji tentang landasan teologis resolusi konflik dari khazanah Sunnah Nabi. Landasan ini penting dikaji sebagai epistemologi dan argumentasi penguatan resolusi konflik dalam rekonstruksi ilmu keislaman di era moderen.',
    keywords: ['resolusi konflik', 'sunnah nabi', 'kearifan lokal', 'hukum Islam', 'islam'],
    openAccess: true,
    pdfUrl: 'https://journal.uinsgd.ac.id/index.php/asy-syariah/article/view/8034',
    contentType: 'html',
    language: 'id',
    type: 'journal',
    subject: 'islamic-law',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2020, 6, 1).toISOString(),
  },
  {
    id: 'article-id-22',
    title: 'From Nonbinding to Binding: Legal Authority Transformation of DSN-MUI Fatwas within the National Legal System',
    authors: [
      { name: 'Muhamad Nasrudin', affiliation: 'Universitas Islam Negeri Jurai Siwo Lampung' },
      { name: 'Ali Sodiqin', affiliation: 'Universitas Islam Negeri Sunan Kalijaga Yogyakarta' },
      { name: 'Abdul Mujib', affiliation: 'Universitas Islam Negeri Sunan Kalijaga Yogyakarta' },
      { name: 'Budhi Santoso', affiliation: 'Universitas Islam Negeri Raden Fatah Palembang' },
    ],
    year: 2025,
    publisher: 'Sharia Faculty, Universitas Islam Negeri KH. Abdurrahamn Wahid Pekalongan',
    journal: 'Jurnal Hukum Islam',
    volume: '23',
    issue: '2',
    pages: '413-458',
    doi: '10.28918/jhi.v23i2.03',
    citationCount: 8,
    abstract: 'In Islamic jurisprudence, a fatwa is nonbinding, even for the person requesting it. However, in the context of Islamic Economic Law in Indonesia, the DSN-MUI fatwa has a strong binding force not only for mustaftis but also for businessmen, regulators, and the government.',
    keywords: ['fatwa DSN-MUI', 'hukum ekonomi Islam', 'otoritas hukum', 'fiqih', 'sistem hukum nasional'],
    openAccess: true,
    pdfUrl: 'https://e-journal.uingusdur.ac.id/jhi/article/view/14060',
    contentType: 'html',
    language: 'en',
    type: 'journal',
    subject: 'islamic-law',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2025, 11, 1).toISOString(),
  },
  {
    id: 'article-id-23',
    title: 'Paradigma Sosial Profetik dalam Kode Etik Politik di Indonesia',
    authors: [
      { name: 'Athoillah Islamy', affiliation: 'IAIN Pekalongan' },
    ],
    year: 2020,
    publisher: 'Institut Agama Islam Negeri Syaikh Abdurrahman Siddik Bangka Belitung',
    journal: 'Asy Syar\'iyyah: Jurnal Ilmu Syariah dan Perbankan Islam',
    volume: '5',
    issue: '2',
    pages: '1-15',
    doi: '10.32923/asy.v5i2.1558',
    citationCount: 10,
    abstract: 'This study aims to reveal social prophetic values in the principles of political ethics in Indonesia. This research is a qualitative research in the form of literature review using Kuntowijoyo\'s social prophetic paradigm theory.',
    keywords: ['paradigma sosial profetik', 'kode etik politik', 'nilai keislaman', 'fiqih', 'politik Islam'],
    openAccess: true,
    pdfUrl: 'https://jurnal.lp2msasbabel.ac.id/index.php/asy/article/view/1558',
    contentType: 'html',
    language: 'en',
    type: 'journal',
    subject: 'islamic-law',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2020, 11, 1).toISOString(),
  },
  {
    id: 'article-id-24',
    title: 'Sejarah Tafsir Nusantara',
    authors: [
      { name: 'Anggi Wahyu Ari', affiliation: 'Fakultas Ushuluddin dan Pemikiran Islam, Universitas Islam Negeri Raden Fatah Palembang' },
    ],
    year: 2020,
    publisher: 'Fakultas Ushuluddin dan Pemikiran Islam, Universitas Islam Negeri Raden Fatah Palembang',
    journal: 'Jurnal Studi Agama',
    volume: '3',
    issue: '2',
    pages: '1-10',
    doi: '10.19109/jsa.v3i2.5131',
    citationCount: 18,
    abstract: 'Perkembangan tafsir Al-Qur\'an Indonesia sangat berbeda dengan di dunia Arab di mana ilmu tersebut lahir, perbedaan ini terjadi karena Indonesia memiliki budaya dan bahasa yang berbeda dengan Arab. Penelitian mendalam menunjukkan bahwa perkembangan sejarah tafsir di Indonesia dapat dilacak melalui sejarah masuknya Islam ke Nusantara.',
    keywords: ['tafsir', 'nusantara', 'penyebaran Islam', 'sejarah Islam', 'Al-Quran'],
    openAccess: true,
    pdfUrl: 'https://jurnal.radenfatah.ac.id/index.php/jsa/article/view/5131',
    contentType: 'html',
    language: 'id',
    type: 'journal',
    subject: 'islamic-studies',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2020, 1, 1).toISOString(),
  },
  {
    id: 'article-id-25',
    title: 'Pengaruh Ide Pembaharuan Abduh di Mesir pada Tradisi Tafsir di Indonesia: Kajian terhadap Tafsir Qur\'an Karim Karya Mahmud Yunus',
    authors: [
      { name: 'Rosihon Anwar', affiliation: 'UIN Sunan Gunung Djati Bandung' },
      { name: 'Asep Abdul Muhyi', affiliation: 'UIN Sunan Gunung Djati Bandung' },
      { name: 'Irma Riyani', affiliation: 'UIN Sunan Gunung Djati Bandung' },
    ],
    year: 2020,
    publisher: 'UIN Antasari Banjarmasin',
    journal: 'Khazanah: Jurnal Studi Islam dan Humaniora',
    volume: '18',
    issue: '2',
    pages: '221-242',
    doi: '10.18592/khazanah.v18i2.3825',
    citationCount: 25,
    abstract: 'Kajian tafsir di Indonesia memiliki keterkaitan yang erat dengan pemikiran tafsir di Timur Tengah. Penelitian ini menunjukkan bahwa pengaruh pembaharuan Abduh terlihat dalam penafsiran yang dilakukan oleh Mahmud Yunus dalam Tafsirnya berkaitan dengan beberapa aspek diantaranya adalah penolakan atas taqlid, bid\'ah dan khurafat.',
    keywords: ['tafsir', 'pembaharuan', 'Abduh', 'Mahmud Yunus', 'Indonesia', 'Mesir'],
    openAccess: true,
    pdfUrl: 'http://jurnal.uin-antasari.ac.id/index.php/khazanah/article/view/3825',
    contentType: 'html',
    language: 'id',
    type: 'journal',
    subject: 'islamic-studies',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2020, 11, 1).toISOString(),
  },
  {
    id: 'article-id-26',
    title: 'Solusi Al-Quran dalam Mengatasi Bahaya Hoaks pada Era Digital (Perspektif Tafsir Al-Misbah)',
    authors: [
      { name: 'Panji Ansari', affiliation: 'Universitas Islam Negeri Antasari Banjarmasin' },
      { name: 'Muhammad Torieq Abdillah', affiliation: 'Universitas Islam Negeri Antasari Banjarmasin' },
    ],
    year: 2022,
    publisher: 'Antasari State Islamic University',
    journal: 'Mu\'asharah',
    volume: '4',
    issue: '2',
    pages: '79-85',
    doi: '10.18592/msr.v4i2.7802',
    citationCount: 12,
    abstract: 'Dari masa ke masa, fenomena adanya hoaks selalu ada dan kini meningkat akibat adanya perkembangan dan kemajuan ilmu pengetahuan dan teknologi secara masif. Penelitian ini menggunakan metode kepustakaan dengan sumber primer, yaitu Tafsir al-Misbah.',
    keywords: ['Al-Quran', 'hoaks', 'tafsir al-misbah', 'digital', 'tabayun'],
    openAccess: true,
    pdfUrl: 'http://jurnal.uin-antasari.ac.id/index.php/muasharah/article/view/7802',
    contentType: 'html',
    language: 'id',
    type: 'journal',
    subject: 'islamic-studies',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2022, 11, 1).toISOString(),
  },
  {
    id: 'article-id-27',
    title: 'The Living Qur\'an: Tradisi Yasinan pada Acara Ahlen',
    authors: [
      { name: 'Nurul Fithriyah Awaliatul Laili', affiliation: 'Universitas Islam Negeri Sunan Kalijaga Yogyakarta' },
    ],
    year: 2021,
    publisher: 'Universitas Muhammadiyah Yogyakarta',
    journal: 'Jurnal Studi Islam dan Kemuhammadiyahan',
    volume: '1',
    issue: '2',
    pages: '1-15',
    doi: '10.18196/jasika.v1i2.11',
    citationCount: 8,
    abstract: 'Artikel ini dilatarbelakangi oleh perlunya pemahaman kepada masyarakat luas tentang tradisi Yasinan. Tradisi ini merupakan tradisi lama yang masih dipegang teguh oleh masyarakat Indonesia utamanya kaum Nahdliyin.',
    keywords: ['living quran', 'tradisi yasinan', 'ahlen', 'Al-Quran', 'pesantren'],
    openAccess: true,
    pdfUrl: 'https://jasika.umy.ac.id/index.php/jasika/article/view/11',
    contentType: 'html',
    language: 'id',
    type: 'journal',
    subject: 'islamic-studies',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2021, 8, 1).toISOString(),
  },
  {
    id: 'article-id-28',
    title: 'Studi Kitab Hadis Nusantara: Kitab Jawahir al-Ahadis Karya Buya Mawardi Muhammad',
    authors: [
      { name: 'Muhammad Alan Juhri', affiliation: 'UIN Sunan Kalijaga' },
    ],
    year: 2019,
    publisher: 'Program Studi Ilmu Hadis',
    journal: 'Jurnal Living Hadis',
    volume: '4',
    issue: '2',
    pages: '253-276',
    doi: '10.14421/livinghadis.2019.1636',
    citationCount: 14,
    abstract: 'Buya Mawardi Muhammad merupakan seorang ulama yang cukup tersohor di Indonesia pada abad ke-20 M, terutama di ranah asalnya, Minangkabau. Tulisan ini membahas karyanya yang monumental di bidang hadis yang berjudul Jawahir al-Ahadis al-Nabawiyyah.',
    keywords: ['hadis', 'nusantara', 'buya mawardi', 'jawahir al-ahadis', 'kitab hadis'],
    openAccess: true,
    pdfUrl: 'http://ejournal.uin-suka.ac.id/ushuluddin/Living/article/view/1636',
    contentType: 'html',
    language: 'id',
    type: 'journal',
    subject: 'islamic-studies',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2019, 9, 1).toISOString(),
  },
  {
    id: 'article-id-29',
    title: 'Kualitas dan Karakteristik Hadis-Hadis Bayan Tafsir Al Quran dalam Fikih Kewarisan',
    authors: [
      { name: 'Maizuddin Maizuddin', affiliation: 'Prodi Ilmu Al-Qur\'an dan Tafsir, UIN Ar-Raniry, Banda Aceh' },
    ],
    year: 2015,
    publisher: 'Fakultas Ushuluddin dan Filsafat UIN Ar-Raniry, Banda Aceh',
    journal: 'Substantia: Jurnal Ilmu-Ilmu Ushuluddin',
    volume: '17',
    issue: '2',
    pages: '167-178',
    doi: '10.22373/substantia.v17i2.3989',
    citationCount: 20,
    abstract: 'Salah satu fungsi hadis adalah bayan tafsir, yaitu memperjelas, merinci, membatasi atau memperluas apa yang disebutkan dalam al-Qur\'an. Kesimpulan hukum fikih telah banyak dihasilkan berdasarkan fungsi bayan tafsir hadis, termasuk di bidang kewarisan.',
    keywords: ['hadis', 'bayan tafsir', 'kualitas hadis', 'fikih kewarisan', 'ushuluddin'],
    openAccess: true,
    pdfUrl: 'https://jurnal.ar-raniry.ac.id/index.php/substantia/article/view/3989',
    contentType: 'html',
    language: 'id',
    type: 'journal',
    subject: 'islamic-studies',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2015, 9, 1).toISOString(),
  },
  {
    id: 'article-id-30',
    title: 'Integrasi Pengetahuan Umum dan Keislaman di Indonesia: Studi Integrasi Keilmuan di Universitas Islam Negeri',
    authors: [
      { name: 'Miftahuddin', affiliation: 'Institut Agama Islam Negeri (IAIN) Salatiga' },
    ],
    year: 2016,
    publisher: 'Institut Agama Islam Negeri (IAIN) Salatiga',
    journal: 'Attarbiyah: Journal of Islamic Culture and Education',
    volume: '1',
    issue: '1',
    pages: '89-118',
    doi: '',
    citationCount: 30,
    abstract: 'Penelitian ini bertujuan untuk mengetahui pelaksanaan konsep integrasi pengetahuan pada tiga Universitas Islam Negeri di Indonesia yaitu UIN Jakarta, UIN Yogyakarta, dan UIN Malang, sehingga menghasilkan model pengetahuan terintegrasi.',
    keywords: ['integrasi keilmuan', 'UIN', 'pendidikan Islam', 'tauhid', 'ilmu keislaman'],
    openAccess: true,
    pdfUrl: 'http://attarbiyah.iainsalatiga.ac.id/index.php/attarbiyah/article/view/556',
    contentType: 'html',
    language: 'en',
    type: 'journal',
    subject: 'islamic-studies',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2016, 10, 1).toISOString(),
  },
  {
    id: 'article-id-31',
    title: 'Pendidikan Islam dalam Masyarakat Madani Indonesia',
    authors: [
      { name: 'Irfan Charis', affiliation: 'Institut Agama Islam Negeri (IAIN) Salatiga' },
      { name: 'Mohamad Nuryansah', affiliation: 'Institut Agama Islam Negeri (IAIN) Salatiga' },
    ],
    year: 2015,
    publisher: 'Institut Agama Islam Negeri (IAIN) Salatiga',
    journal: 'Mudarrisa: Jurnal Kajian Pendidikan Islam',
    volume: '7',
    issue: '2',
    pages: '229-258',
    doi: '',
    citationCount: 22,
    abstract: 'Tulisan ini bertujuan untuk memetakan konsep, gagasan dan pola pendidikan Islam dalam masyarakat madani di Indonesia, dengan berpijak pada konsep pendidikan dan masyarakat madani dari aspek kesejarahan dan kenabian.',
    keywords: ['pendidikan Islam', 'masyarakat madani', 'ulul albab', 'tauhid', 'indonesia'],
    openAccess: true,
    pdfUrl: 'http://attarbiyah.iainsalatiga.ac.id/index.php/mudarrisa/article/view/755',
    contentType: 'html',
    language: 'id',
    type: 'journal',
    subject: 'islamic-studies',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2015, 11, 1).toISOString(),
  },
  {
    id: 'article-id-32',
    title: 'Implementation of Tafsir Ulul Albab in Indonesian Islamic Education',
    authors: [
      { name: 'Rofiq Nurhadi', affiliation: 'Universitas Muhamamadiyah Purworejo' },
      { name: 'Huseyin Emin Sert', affiliation: 'Istanbul Medeniyet Universitesi' },
      { name: 'Jarot Wahyudi', affiliation: 'Universitas Islam Negeri Sunan Kalijaga Yogyakarta' },
    ],
    year: 2024,
    publisher: 'Indonesian Academy of Social and Religious Research (IASRR)',
    journal: 'International Journal of Social Science and Religion',
    volume: '5',
    issue: '2',
    pages: '1-15',
    doi: '10.53639/ijssr.v5i2.220',
    citationCount: 6,
    abstract: 'Islam views the holy book as not only regulating matters of worship which are vertical between servants and God. The holy book is also seen as a guide for humans in managing all world affairs, including the world of education.',
    keywords: ['ulul albab', 'tafsir', 'pendidikan Islam', 'integrasi', 'Indonesia'],
    openAccess: true,
    pdfUrl: 'https://ijssr.net/index.php/ijssr/article/view/220',
    contentType: 'html',
    language: 'en',
    type: 'journal',
    subject: 'islamic-studies',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2024, 4, 1).toISOString(),
  },
  {
    id: 'article-id-33',
    title: 'Peran Sekolah Alam Cordova Terhadap Dinamika Keagamaan Masyarakat Kota Probolinggo',
    authors: [
      { name: 'Moch. Mukhlison', affiliation: 'Institut Agama Islam Tribakti Kediri' },
    ],
    year: 2018,
    publisher: 'Institut Agama Islam Tribakti Kediri',
    journal: 'Tribakti: Jurnal Pemikiran Keislaman',
    volume: '29',
    issue: '2',
    pages: '407-424',
    doi: '10.33367/tribakti.v29i2.605',
    citationCount: 9,
    abstract: 'Penelitian tentang gerakan radikalisme dalam dunia pendidikan semakin menguat selama dua dekade terakhir ini. Penelitian ini menggunakan pendekatan kualitatif berperspektif ideologi pendidikan.',
    keywords: ['dakwah', 'pendidikan Islam', 'moderatisme', 'konservatisme', 'radikalisme'],
    openAccess: true,
    pdfUrl: 'https://ejournal.iai-tribakti.ac.id/index.php/tribakti/article/view/605',
    contentType: 'html',
    language: 'id',
    type: 'journal',
    subject: 'islamic-studies',
    source: 'DOAJ (Indonesia)',
    createdAt: new Date(2018, 6, 1).toISOString(),
  },
  {
    id: 'article-id-34',
    title: 'EKOLITERASI DALAM PENAFSIRAN AL-QUR\'AN',
    authors: [
      { name: 'Imam Syafi\'i', affiliation: 'UINSI Samarinda' },
      { name: 'Fathir Hazazi', affiliation: 'UINSI Samarinda' },
    ],
    year: 2026,
    publisher: 'UINSI Samarinda',
    journal: 'Jurnal Ilmu Al-Qur\'an dan Tafsir',
    volume: '1',
    issue: '1',
    pages: '1-15',
    doi: '',
    citationCount: 0,
    abstract: 'Makalah ini membahas konsep ekoliterasi dalam penafsiran Al-Qur\'an, mengeksplorasi bagaimana Al-Qur\'an memberikan panduan tentang menjaga dan melestarikan lingkungan hidup. Penelitian ini mengkaji ayat-ayat Al-Qur\'an yang berkaitan dengan ekologi dan lingkunganhidup dari perspektif tafsir kontemporer.',
    keywords: ['ekoliterasi', 'tafsir Al-Qur\'an', 'lingkungan hidup', 'ekologi Islam', 'penafsiran'],
    openAccess: true,
    pdfUrl: 'https://drive.google.com/uc?export=download&id=12WwAy1_qnjFjSZJ5H9WK_1UtVXbHXsPT',
    contentType: 'html',
    language: 'id',
    type: 'article',
    subject: 'islamic-studies',
    source: 'Custom Article',
    createdAt: new Date(2026, 0, 1).toISOString(),
  },
  {
    id: 'article-id-35',
    title: 'KAJIAN KRITIS AL-DAKHIL JALUR SAHABAT DAN TABI\'IN',
    authors: [
      { name: 'Ratna Hardiyanti', affiliation: 'UINSI Samarinda' },
      { name: 'Nadila', affiliation: 'UINSI Samarinda' },
      { name: 'Muhammad Rizqan', affiliation: 'UINSI Samarinda' },
    ],
    year: 2026,
    publisher: 'UINSI Samarinda',
    journal: 'Jurnal Ilmu Al-Qur\'an dan Tafsir',
    volume: '1',
    issue: '1',
    pages: '1-20',
    doi: '',
    citationCount: 0,
    abstract: 'Al-Dakhil adalah istilah untuk ajaran atau pemikiran asing yang masuk ke dalam Islam dan dapat merusak pemahaman yang benar terhadap Al-Qur\'an. Makalah ini mengkaji secara kritis fenomena al-dakhil pada masa sahabat dan tabi\'in, khususnya melalui jalur riwayat. Penelitian ini menggunakan metode kualitatif deskriptif dengan pendekatan kepustakaan. Hasil kajian menunjukkan bahwa infiltrasi pemikiran asing sudah mulai terjadi sejak masa tabi\'in, terutama melalui masuknya riwayat Israiliyyat yang tidak valid dan pendapat sahabat serta tabi\'in yang tidak dapat dipertanggungjawabkan. Kajian ini penting untuk menjaga otensitas penafsiran Al-Qur\'an agar terhindar dari kontaminasi pemikiran yang menyimpang.',
    keywords: ['al-dakhil', 'tafsir', 'sahabat', 'tabi\'in', 'Israiliyyat', 'kritik tafsir'],
    openAccess: true,
    pdfUrl: 'https://drive.google.com/uc?export=download&id=1mVCCAs0E90M9X0mPqWDyeuiVptLs9jGS',
    contentType: 'html',
    language: 'id',
    type: 'article',
    subject: 'islamic-studies',
    source: 'Custom Article',
    createdAt: new Date(2026, 0, 1).toISOString(),
  },
];

const internationalArticles: Article[] = Array.from({ length: 40 }, (_, i) => ({
  id: `article-${i + 1}`,
  title: [
    'Deep Learning Applications in Natural Language Processing: A Comprehensive Survey',
    'Machine Learning Approaches for Climate Change Prediction and Modeling',
    'Blockchain Technology for Secure Healthcare Data Management: A Systematic Review',
    'Advances in Reinforcement Learning: From Games to Real-World Applications',
    'Quantum Computing: Current State and Future Directions in Quantum Algorithms',
    'Artificial Intelligence in Education: Personalized Learning Paths and Adaptive Assessment',
    'Internet of Things (IoT) Security Challenges and Solutions: A Systematic Literature Review',
    'CRISPR-Cas9 Gene Editing: Ethical Considerations and Regulatory Frameworks',
    'Sustainable Energy Systems: A Review of Renewable Energy Integration Technologies',
    'Big Data Analytics in Smart Cities: Applications, Challenges, and Research Opportunities',
  ][i % 10],
  authors: [
    { name: 'Dr. Sarah Mitchell', affiliation: 'Stanford University' },
    { name: 'Prof. James Anderson', affiliation: 'MIT' },
    { name: 'Dr. Maria Rodriguez', affiliation: 'University of Cambridge' },
    { name: 'Prof. Chen Wei', affiliation: 'Tsinghua University' },
  ].slice(0, (i % 4) + 1),
  year: 2026 - (i % 5),
  publisher: ['IEEE', 'Springer Nature', 'Elsevier', 'ACM', 'Oxford University Press'][i % 5],
  journal: [
    'Nature Communications',
    'IEEE Transactions on Pattern Analysis',
    'Journal of Artificial Intelligence Research',
    'Proceedings of the National Academy of Sciences',
    'The Lancet Digital Health',
  ][i % 5],
  volume: `Vol. ${i + 10}`,
  issue: `No. ${(i % 12) + 1}`,
  pages: `${i * 10 + 100}-${i * 10 + 120}`,
  doi: `10.1234/imamsyafiihub.2026.${i + 1}`,
  citationCount: Math.floor(Math.random() * 500),
  abstract: `This paper presents a comprehensive review and analysis of recent advances in the field. We examine the current state of research, identify key challenges, and propose future directions for investigation. Our systematic analysis covers ${Math.floor(Math.random() * 100 + 50)} studies published between ${2020 + (i % 3)} and ${2026 - (i % 2)}. The findings suggest significant progress has been made, though several critical gaps remain in the literature. This review provides valuable insights for researchers and practitioners working in this rapidly evolving domain.`,
  keywords: [
    ['deep learning', 'NLP', 'machine learning', 'survey'],
    ['climate change', 'machine learning', 'prediction', 'environmental science'],
    ['blockchain', 'healthcare', 'security', 'systematic review'],
    ['reinforcement learning', 'AI', 'real-world applications'],
    ['quantum computing', 'algorithms', 'quantum algorithms'],
    ['AI in education', 'personalized learning', 'adaptive assessment'],
    ['IoT security', 'cybersecurity', 'literature review'],
    ['CRISPR', 'gene editing', 'ethics', 'regulation'],
    ['sustainable energy', 'renewable energy', 'smart grid'],
    ['big data', 'smart cities', 'data analytics'],
  ][i % 10],
  openAccess: i % 3 === 0,
  pdfUrl: i % 2 === 0 ? `https://example.com/papers/paper-${i + 1}.pdf` : undefined,
  language: ['en', 'en', 'en', 'en', 'en', 'id', 'en', 'en', 'en', 'en'][i % 10],
  quartile: ['q1', 'q1', 'q2', 'q1', 'q2', 'q3', 'q1', 'q2', 'q1', 'q3'][i % 10],
  type: (['journal', 'conference', 'thesis', 'journal', 'article', 'book', 'conference', 'dissertation', 'journal', 'article'] as const)[i % 10],
  subject: ['computer-science', 'environmental-science', 'medicine', 'computer-science', 'physics', 'education', 'engineering', 'biology', 'engineering', 'computer-science'][i % 10],
  source: ['Crossref', 'OpenAlex', 'Semantic Scholar', 'CORE', 'PubMed'][i % 5],
  createdAt: new Date(2026, 0, i + 1).toISOString(),
}));

export const mockArticles: Article[] = [...indonesianArticles, ...internationalArticles];

const mockTrendingKeywords: TrendingKeyword[] = [
  { keyword: 'Artificial Intelligence', count: 15420, trend: 'up' },
  { keyword: 'Machine Learning', count: 12350, trend: 'up' },
  { keyword: 'Pendidikan Indonesia', count: 11200, trend: 'up' },
  { keyword: 'Deep Learning', count: 10200, trend: 'up' },
  { keyword: 'UMKM Digital', count: 8900, trend: 'up' },
  { keyword: 'Blockchain', count: 8750, trend: 'stable' },
  { keyword: 'Merdeka Belajar', count: 8100, trend: 'up' },
  { keyword: 'Climate Change', count: 7200, trend: 'up' },
  { keyword: 'Deteksi Dini Penyakit', count: 6900, trend: 'up' },
  { keyword: 'Pariwisata Berkelanjutan', count: 5600, trend: 'up' },
  { keyword: 'E-Commerce Indonesia', count: 5200, trend: 'up' },
  { keyword: 'Natural Language Processing', count: 4300, trend: 'up' },
];

export async function mockSearch(filters: SearchFilters): Promise<SearchResult> {
  let results = [...mockArticles];
  const q = filters.query.toLowerCase();

  if (q) {
    results = results.filter(a =>
      a.title.toLowerCase().includes(q) ||
      a.authors.some(au => au.name.toLowerCase().includes(q)) ||
      a.abstract.toLowerCase().includes(q) ||
      a.keywords.some(k => k.toLowerCase().includes(q)) ||
      a.doi?.toLowerCase().includes(q) ||
      a.journal?.toLowerCase().includes(q) ||
      a.publisher?.toLowerCase().includes(q)
    );
  }

  if (filters.type) results = results.filter(a => a.type === filters.type);
  if (filters.yearFrom) results = results.filter(a => a.year >= filters.yearFrom!);
  if (filters.yearTo) results = results.filter(a => a.year <= filters.yearTo!);
  if (filters.language) results = results.filter(a => a.language === filters.language);
  if (filters.publisher) { const pub = filters.publisher.toLowerCase(); results = results.filter(a => a.publisher?.toLowerCase().includes(pub)); }
  if (filters.openAccess) results = results.filter(a => a.openAccess);
  if (filters.citationMin) results = results.filter(a => a.citationCount >= filters.citationMin!);
  if (filters.quartile) results = results.filter(a => a.quartile === filters.quartile);
  if (filters.subject) results = results.filter(a => a.subject === filters.subject);

  const total = results.length;
  const perPage = filters.perPage || 10;
  const page = filters.page || 1;
  const totalPages = Math.ceil(total / perPage);
  const start = (page - 1) * perPage;
  const paged = results.slice(start, start + perPage);

  return { articles: paged, total, page, perPage, totalPages };
}

export async function mockGetArticle(id: string): Promise<Article | undefined> {
  return mockArticles.find(a => a.id === id);
}

export async function mockGetTrendingKeywords(): Promise<TrendingKeyword[]> {
  return mockTrendingKeywords;
}

export async function mockGetRelatedArticles(articleId: string): Promise<Article[]> {
  const article = mockArticles.find(a => a.id === articleId);
  if (!article) return [];
  return mockArticles
    .filter(a => a.id !== articleId && a.keywords.some(k => article.keywords.includes(k)))
    .slice(0, 5);
}

export async function mockGetCitations(): Promise<Citation> {
  return {
    apa: 'Mitchell, S., Anderson, J., & Rodriguez, M. (2026). Deep Learning Applications in Natural Language Processing: A Comprehensive Survey. Nature Communications, 15(1), 100-112.',
    mla: 'Mitchell, Sarah, et al. "Deep Learning Applications in Natural Language Processing: A Comprehensive Survey." Nature Communications, vol. 15, no. 1, 2026, pp. 100-112.',
    ieee: 'S. Mitchell, J. Anderson, and M. Rodriguez, "Deep Learning Applications in Natural Language Processing: A Comprehensive Survey," Nature Communications, vol. 15, no. 1, pp. 100-112, 2026.',
    chicago: 'Mitchell, Sarah, James Anderson, and Maria Rodriguez. "Deep Learning Applications in Natural Language Processing: A Comprehensive Survey." Nature Communications 15, no. 1 (2026): 100-112.',
    harvard: 'Mitchell, S., Anderson, J. and Rodriguez, M. (2026). Deep Learning Applications in Natural Language Processing: A Comprehensive Survey. Nature Communications, 15(1), pp. 100-112.',
    bibtex: '@article{mitchell2026deep,\n  title={Deep Learning Applications in Natural Language Processing: A Comprehensive Survey},\n  author={Mitchell, Sarah and Anderson, James and Rodriguez, Maria},\n  journal={Nature Communications},\n  volume={15},\n  number={1},\n  pages={100--112},\n  year={2026}\n}',
    ris: 'TY  - JOUR\nAU  - Mitchell, Sarah\nAU  - Anderson, James\nAU  - Rodriguez, Maria\nPY  - 2026\nTI  - Deep Learning Applications in Natural Language Processing\nT2  - Nature Communications\nVL  - 15\nIS  - 1\nSP  - 100\nEP  - 112\nER  -',
  };
}

export const mockUser: User = {
  id: 'user-1',
  email: 'researcher@example.com',
  name: 'Dr. Alex Researcher',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
  role: 'user',
  createdAt: '2025-01-01T00:00:00Z',
};

export const mockBookmarks: UserBookmark[] = mockArticles.slice(0, 5).map((a, i) => ({
  id: `bookmark-${i + 1}`,
  articleId: a.id,
  article: a,
  folder: i < 3 ? 'Machine Learning' : 'General',
  createdAt: new Date(2026, 0, i + 1).toISOString(),
}));

export const mockHistory: UserHistory[] = [
  { id: 'hist-1', query: 'deep learning NLP survey', createdAt: new Date(2026, 6, 20).toISOString() },
  { id: 'hist-2', query: 'blockchain healthcare', createdAt: new Date(2026, 6, 19).toISOString() },
  { id: 'hist-3', query: 'quantum computing algorithms', createdAt: new Date(2026, 6, 18).toISOString() },
  { id: 'hist-4', query: 'climate change prediction ML', createdAt: new Date(2026, 6, 17).toISOString() },
  { id: 'hist-5', query: 'CRISPR ethics regulation', createdAt: new Date(2026, 6, 16).toISOString() },
];

export const mockDashboardStats: DashboardStats = {
  totalBookmarks: 23,
  totalSearches: 147,
  totalCitations: 89,
  recentActivity: [
    { id: 'act-1', type: 'search', description: 'Searched for "deep learning"', createdAt: new Date().toISOString() },
    { id: 'act-2', type: 'bookmark', description: 'Saved "Advances in Reinforcement Learning"', createdAt: new Date(Date.now() - 3600000).toISOString() },
    { id: 'act-3', type: 'citation', description: 'Exported citation in APA format', createdAt: new Date(Date.now() - 7200000).toISOString() },
    { id: 'act-4', type: 'download', description: 'Downloaded PDF of "Quantum Computing"', createdAt: new Date(Date.now() - 10800000).toISOString() },
  ],
};
